function var_err=variance_error(J,W)
N=size(W,1);
W(logical(eye(size(W))))=nan;
[~,alph]=finderror_lsq(100,W,J,'av',1);
J=alph*J;
J(logical(eye(size(J))))=nan;
J=circular_shift(J);
J=J(:,[1:49 51:end]);
var_err=sqrt(N*sum(var(J)))/norm(W(~isnan(W)),2);